environment:
  matrix:
    - nodejs_version: 10

cache:
  - node_modules -> package.json
  - app/node_modules -> app/package.json

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm install

build_script:
  - npm run build
  - npm run dist-win

test: off



