environment:
  my_variable:
    secure: GMi338wQhb8u5AxIWKpMSA==

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 8 x64
  - npm install

build_script:
  - npm run dll-prod && npm run build-prod && npm run dist-win

test: off

branches:
  only:
    - /^v\d+(\.\d+)+$/
