export const UPDATE_NOT_CHECKED = Symbol('UPDATE_NOT_CHECKED');
export const UPDATE_CHECKING = Symbol('UPDATE_CHECKING');
export const UPDATE_AVAILABLE = Symbol('UPDATE_AVAILABLE');
export const UPDATE_NOT_AVAILABLE = Symbol('UPDATE_NOT_AVAILABLE');
export const UPDATE_DOWNLOADING = Symbol('UPDATE_DOWNLOADING');
export const UPDATE_DOWNLOADED = Symbol('UPDATE_DOWNLOADED');
export const UPDATE_DOWNLOAD_ERROR = Symbol('UPDATE_DOWNLOAD_ERROR');
